contatos/urls.py
from django.urls import path

from . import views

app_name = 'contatos'

urlpatterns = [
    path('contato/', views.contato, name='padrao'),
    path('lgpd/', views.lgpd, name='lgpd'),
]

paginas/urls.py
from django.urls import path

from . import views

app_name = "paginas"

urlpatterns = [
    path("", views.index, name="index"),
    path("descartar/", views.descartes, name="lista_descartar"),
    path(
        "coletar/",
        views.coletas,
        name="lista_coletar",
    ),
    path("doar/", views.doacoes, name="lista_doar"),
    path("sobre/", views.sobre, name="sobre"),
    path("termos-de-uso/", views.termos_de_uso, name="termos_de_uso"),
    path(
        "politica-de-privacidade/",
        views.politica_de_privacidade,
        name="politica_de_privacidade",
    ),
    # Simula coletores
    path("coletores/sucata-digital", views.coletor1, name="coletor_1"),
    path("coletores/e-mile", views.coletor2, name="coletor_2"),
    path("coletores/bh-recicla", views.coletor3, name="coletor_3"),
    path("coletores/reciclo-inteligencia-ambiental", views.coletor4, name="coletor_4"),
    path("coletores/mg-recicla", views.coletor5, name="coletor_5"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('o-que-e-o-lixo-eletronico', views.post1, name='post-1'),
    path('10-razoes-para-reciclar-o-lixo-eletronico', views.post2, name='post-2'),
    path('como-descartar-o-lixo-eletronico', views.post3, name='post-3'),
]

recicle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('paginas.urls')),
    path('', include('contatos.urls')),
    path('blog/', include('posts.urls')),
    path('mensagens/', include('mensagens.urls')),
    path('perfil/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

# configura a pagina de erro 404
handler404 = "paginas.views.view_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ADMINISTRAÇÃO DO SISTEMA RECICLE!'
admin.site.site_title = 'RECICLE ADMIN'

usuarios/urls.py
from django.urls import path

from . import views

app_name = "perfil"

urlpatterns = [
    path("coletor/novo", views.RegistroColetor.as_view(), name="coletor_registro"),
    path("coletor/editar", views.EditarColetor.as_view(), name="coletor_edicao"),
    path(
        "consumidor/novo",
        views.RegistroConsumidor.as_view(),
        name="consumidor_registro",
    ),
    path(
        "consumidor/editar", views.EditarConsumidor.as_view(), name="consumidor_edicao"
    ),
]

# views relativas ao processo de autenticação e administração se senhas
urlpatterns += [
    path("entrar/", views.UsuarioLoginView.as_view(), name="login"),
    path("sair/", views.UsuarioLogoutView.as_view(), name="logout"),
    path(
        "alterar-senha/",
        views.UsuarioPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "alterar-senha/sucesso/",
        views.UsuarioPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "resetar-senha/",
        views.UsuarioPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "resetar-senha/<uidb64>/<token>/",
        views.UsuarioPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "resetar-senha/concluido/",
        views.UsuarioPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "resetar-senha/sucesso/",
        views.UsuarioPasswordResetDoneView.as_view(),
        name="password_change_done",
    ),
]

templates/includes/favicon.html
{% load static %}
<link type="image/png" sizes="16x16" rel="icon" href="{% static 'images/favicon-16x16.png' %}">
<link type="image/png" sizes="32x32" rel="icon" href="{% static 'images/favicon-32x32.png' %}">
<link type="image/png" sizes="96x96" rel="icon" href="{% static 'images/favicon-96x96.png' %}">
<link type="image/png" sizes="120x120" rel="icon" href="{% static 'images/favicon-120x120.png' %}">

templates/includes/footer.html
{% load static %}

<footer class="mt-auto bg-primary-color">
    <div class="container mx-auto w-10/12 py-16 text-white flex">

        <!-- LOGO: inicio -->
        <div class="flex flex-col items-center w-3/5">
            <a class="py-3" href="{% url 'paginas:index' %}">
                <img src="{% static 'images/logo/recicle-branco.png' %}" alt="">
            </a>
            <p>
                O “Recicle” surgiu em 2020, a partir do desejo de seus idealizadores em contribuir com o meio ambiente.
            </p>
        </div>
        <!-- LOGO: fim -->

        <!-- PAGINAS IMPORTANTES: inicio -->
        <div class="w-1/5">
            <h3 class="font-bold uppercase">Páginas importantes</h3>
            <nav>
                <ul>
                    <li class="hover:text-secondary-color hover:font-bold"><a href="{% url 'paginas:index' %}">Home</a>
                    </li>
                    <li class="hover:text-secondary-color hover:font-bold"><a href="{% url 'paginas:termos_de_uso' %}">Termos
                            de Uso</a></li>
                    <li class="hover:text-secondary-color hover:font-bold"><a
                            href="{% url 'paginas:politica_de_privacidade' %}">Politica de Privacidade</a></li>
                    <li class="hover:text-secondary-color hover:font-bold"><a
                            href="{% url 'contatos:lgpd' %}">LGPD</a>

                    </li>
                </ul>
            </nav>
        </div>
        <!-- PAGINAS IMPORTANTES: fim -->

        <!-- REDES SOCIAIS: inicio -->
        <div class="text-center w-1/5">
            <h3 class="font-bold uppercase">Siga-nos nas redes sociais</h3>
            <a class="text-6xl" href="https://pt-br.facebook.com/" target="_blank">
                <i class="fa fa-facebook-square" aria-hidden="true"></i>
            </a>
        </div>
        <!-- REDES SOCIAIS: fim -->

    </div>
</footer>

<div class="py-1 bg-gray-800 text-white">
    <div class="container mx-auto text-center">
        <p class="text-sm">
            Carinhosamente <i class="fa fa-heart text-red-500" aria-hidden="true"></i> feito por Recicle! - © 2022 Todos
            os direitos reservados.
        </p>
    </div>
</div>

templates/includes/header.html
{% load static %}
<!-- HEADER: inicio -->
<header>
    <!-- BARRA-TOPO: inicio -->
    <div class="container-fluid w-full bg-primary-color py-1">
        <div class="container flex justify-end mx-auto text-white text-xs font-bold">
            <!-- BARRA-TOPO LINKS -->
            <nav>
                <ul class="flex">
                    <li class="m-1 hover:text-green-900"><a href="{% url 'paginas:sobre' %}">Sobre</a></li>
                    <li class="m-1 hover:text-green-900"><a href="{% url 'contatos:padrao' %}">Contato</a></li>
                </ul>
            </nav>
            <!-- BARRA-TOPO WHATSAPP -->
            <span class="bg-secondary-color h-full py-1 px-2">
                <a href="https://www.whatsapp.com/?lang=pt_br" target="_blank">
                    <i class="fa fa-whatsapp" aria-hidden="true"></i>
                    <span>(31) 3344-5566</span>
                </a>
            </span>
        </div>
    </div>
    <!-- BARRA-TOPO: fim -->

    <!-- MENU: inicio -->
    <div class="w-full bg-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-3 text-xs font-bold">
            <div>
                <a href="{% url 'paginas:index' %}">
                    <img class="w-full" src="{% static 'images/logo/recicle.png' %}" alt="RECICLE LOGOTIPO">
                </a>
            </div>
            <div>
                <nav>
                    <ul class="flex items-center">
                        <li class="m-1"><a class="uppercase hover:text-primary-color"
                                href="{% url 'paginas:index' %}">HOME</a></li>
                        <li class="m-1"><a class="uppercase hover:text-primary-color"
                                href="{% url 'paginas:lista_descartar' %}">DESCARTAR</a></li>
                        <li class="m-1"><a class="uppercase hover:text-primary-color"
                                href="{% url 'paginas:lista_doar' %}">DOAR</a></li>
                        <li class="m-1"><a class="uppercase hover:text-primary-color"
                                href="{% url 'posts:blog' %}">BLOG</a></li>

                        {% if request.user.is_authenticated %}
                            {% if not request.user.is_staff %}
                            <li class="m-1">
                                <a class="text-white rounded-lg bg-secondary-color p-3" href="{% url 'perfil:coletor_edicao' %}">
                                    <span class="uppercase"> EDITAR PERFIL</span>
                                </a>
                            </li>
                            {% endif %}
                        {% endif %}
                        

                        {% if request.user.is_authenticated %}
                        <li class="m-1">
                            <span class="uppercase text-primary-color">Olá, {{ request.user }}</span>
                        </li>
                        {% endif %}
                        {% if request.user.is_staff %}
                        <li class="m-1">
                            <a class="text-white bg-secondary-color p-3" href="{% url 'admin:index' %}">
                                <i class="fa fa-cogs" aria-hidden="true"></i>
                                <span class="uppercase"> ADMINISTRAÇÃO</span>
                            </a>
                        </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li class="m-1">
                            <a class="hover:text-primary-color" href="{% url 'perfil:logout' %}">
                                <i class="fa fa-sign-out text-secondary-color" aria-hidden="true"></i>
                                <span class="uppercase">SAIR</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="m-1">
                            <a class="hover:text-primary-color" href="{% url 'perfil:login' %}">
                                <i class="fa fa-sign-in text-secondary-color" aria-hidden="true"></i>
                                <span class="uppercase">ENTRAR</span>
                            </a>
                        </li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- MENU: fim -->
</header>
<!-- HEADER: fim -->

templates/includes/header_simples.html
{% load static %}
    <!-- HEADER: inicio -->

    <header class="">
        <!-- BARRA: inicio -->
        <div class="w-full bg-primary-color shadow-lg">
            <div class="container py-3 flex justify-between mx-auto  text-white text-xs font-bold">

                <!-- BARRA LOGO -->
                <div>
                    <a href="{% url 'paginas:index' %}">
                        <img class="w-32" src="{% static 'images/logo/recicle-branco.png' %}" alt="RECICLE LOGOTIPO">
                    </a>
                </div>

                <!-- BARRA LINKS -->
                <nav class="flex flex-col self-center justify-center">
                    <ul>
                       <li class="m-1 uppercase hover:text-green-900"><a href="{% url 'contatos:padrao' %}">Contato</a></li>
                    </ul>
                </nav>

            </div>
        </div>
        <!-- BARRA: fim -->

    </header>
    <!-- HEADER: fim -->

templates/includes/pagination.html
<div class="paginacao">
    <span class="step-links">
        {% if pagina.has_previous %}
            <a href="?page={{ pagina.previous_page_number }}">Anterior</a>
        {% endif %}
        <span class="current">
            Pagina {{ pagina.number }} de {{ pagina.paginator.num_pages }}.
        </span>
        {% if pagina.has_next %}
            <a href="?page={{ pagina.next_page_number }}">Próximo</a>
        {% endif %}
    </span>
</div>