paginas/urls.py
from django.urls import path

from . import views

app_name = "paginas"

urlpatterns = [
    path("", views.index, name="index"),
    path("descartar/", views.descartes, name="lista_descartar"),
    path(
        "coletar/",
        views.coletas,
        name="lista_coletar",
    ),
    path("doar/", views.doacoes, name="lista_doar"),
    path("sobre/", views.sobre, name="sobre"),
    path("termos-de-uso/", views.termos_de_uso, name="termos_de_uso"),
    path(
        "politica-de-privacidade/",
        views.politica_de_privacidade,
        name="politica_de_privacidade",
    ),
    # Simula coletores
    path("coletores/sucata-digital", views.coletor1, name="coletor_1"),
    path("coletores/e-mile", views.coletor2, name="coletor_2"),
    path("coletores/bh-recicla", views.coletor3, name="coletor_3"),
    path("coletores/reciclo-inteligencia-ambiental", views.coletor4, name="coletor_4"),
    path("coletores/mg-recicla", views.coletor5, name="coletor_5"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('o-que-e-o-lixo-eletronico', views.post1, name='post-1'),
    path('10-razoes-para-reciclar-o-lixo-eletronico', views.post2, name='post-2'),
    path('como-descartar-o-lixo-eletronico', views.post3, name='post-3'),
]

recicle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('paginas.urls')),
    path('', include('contatos.urls')),
    path('blog/', include('posts.urls')),
    path('mensagens/', include('mensagens.urls')),
    path('perfil/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

# configura a pagina de erro 404
handler404 = "paginas.views.view_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ADMINISTRAÇÃO DO SISTEMA RECICLE!'
admin.site.site_title = 'RECICLE ADMIN'

usuarios/urls.py
from django.urls import path

from . import views

app_name = "perfil"

urlpatterns = [
    path("coletor/novo", views.RegistroColetor.as_view(), name="coletor_registro"),
    path("coletor/editar", views.EditarColetor.as_view(), name="coletor_edicao"),
    path(
        "consumidor/novo",
        views.RegistroConsumidor.as_view(),
        name="consumidor_registro",
    ),
    path(
        "consumidor/editar", views.EditarConsumidor.as_view(), name="consumidor_edicao"
    ),
]

# views relativas ao processo de autenticação e administração se senhas
urlpatterns += [
    path("entrar/", views.UsuarioLoginView.as_view(), name="login"),
    path("sair/", views.UsuarioLogoutView.as_view(), name="logout"),
    path(
        "alterar-senha/",
        views.UsuarioPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "alterar-senha/sucesso/",
        views.UsuarioPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "resetar-senha/",
        views.UsuarioPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "resetar-senha/<uidb64>/<token>/",
        views.UsuarioPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "resetar-senha/concluido/",
        views.UsuarioPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "resetar-senha/sucesso/",
        views.UsuarioPasswordResetDoneView.as_view(),
        name="password_change_done",
    ),
]

paginas/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.text import slugify


class Pagina(models.Model):

    STATUS = (
        ('rascunho', 'Rascunho'),
        ('publicado', 'Publicado'),
    )

    titulo = models.CharField(
        verbose_name="Título",
        max_length=255
    )

    slug = models.SlugField(
        max_length=255
    )

    autor = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    conteudo_pagina = models.TextField(
        verbose_name="Conteúdo"
    )
  
    data_criacao = models.DateTimeField(
        auto_now_add=True
    )

    data_modificacao = models.DateTimeField(
        auto_now=True
    )

    publicacao = models.DateTimeField(
        default=timezone.now
    )

    status = models.CharField(max_length=10,
                              choices=STATUS,
                              default='rascunho')

    
    class Meta:
        ordering = ['-publicacao']

    def __str__(self):
        return self.titulo


@receiver(post_save, sender=Pagina)
def insert_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.titulo)
        return instance.save()

paginas/forms.py
from django import forms

# create your form here

paginas/views.py
from django.shortcuts import render

from . import forms


# página inicial
def index(request):
    return render(request, "paginas/index.html")


# página de listagem para descarte
def descartes(request):
    return render(request, "paginas/listagem/descartes.html")


# página de listagem para doações
def doacoes(request):
    return render(request, "paginas/listagem/doacoes.html")


# página de cadastro de coletor
def coletas(request):
    return render(request, "paginas/listagem/coletor_registro.html")


# página sobre
def sobre(request):
    return render(request, "paginas/sobre.html")


# página de termos de uso
def termos_de_uso(request):
    return render(request, "paginas/termos_de_uso.html")


# página de politica de privacidade
def politica_de_privacidade(request):
    return render(request, "paginas/politica_de_privacidade.html")


# página para error 404 (página não encontrada)
def view_404(request, exception):
    return render(request, "not_found.html")


# Simulação de coletores
def coletor1(request):
    return render(request, "paginas/coletores_detalhes/coletor_1.html")


def coletor2(request):
    return render(request, "paginas/coletores_detalhes/coletor_2.html")


def coletor3(request):
    return render(request, "paginas/coletores_detalhes/coletor_3.html")


def coletor4(request):
    return render(request, "paginas/coletores_detalhes/coletor_4.html")


def coletor5(request):
    return render(request, "paginas/coletores_detalhes/coletor_5.html")

paginas/templates/paginas/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! – Seja bem-vindo!{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/flowbite.min.css' %}">
{% endblock %}

{% block header %}
    {% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

<!-- CAROUSEL inicio -->
<div class="relative">
    <!-- Carousel wrapper -->
    <div class="overflow-hidden relative h-56 sm:h-64 xl:h-80 2xl:h-96">
        <!-- Item 1 -->
        <div id="carousel-item-1" class="duration-1000 ease-in-out">
            <span
                class="absolute top-1/2 left-1/2 text-2xl font-semibold text-white -translate-x-1/2 -translate-y-1/2 sm:text-3xl dark:text-gray-800">Primeiro
                Slide</span>
            <img src="{% static 'images/carousel/imagem-1.jpg' %}"
                class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
        <!-- Item 2 -->
        <div id="carousel-item-2" class="hidden duration-1000 ease-in-out">
            <img src="{% static 'images/carousel/imagem-2.jpg' %}"
                class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
        <!-- Item 3 -->
        <div id="carousel-item-3" class="hidden duration-1000 ease-in-out">
            <img src="{% static 'images/carousel/imagem-3.jpg' %}"
                class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
    </div>
    <!-- Slider indicators -->
    <div class="flex absolute bottom-5 left-1/2 z-30 space-x-3 -translate-x-1/2">
        <button id="carousel-indicator-1" type="button" class="w-3 h-3 rounded-full" aria-current="true"
            aria-label="Slide 1"></button>
        <button id="carousel-indicator-2" type="button" class="w-3 h-3 rounded-full" aria-current="false"
            aria-label="Slide 2"></button>
        <button id="carousel-indicator-3" type="button" class="w-3 h-3 rounded-full" aria-current="false"
            aria-label="Slide 3"></button>
    </div>
    <!-- Slider controls -->
    <button id="data-carousel-prev" type="button"
        class="flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none">
        <span
            class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor"
                viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
            </svg>
            <span class="hidden">Previous</span>
        </span>
    </button>
    <button id="data-carousel-next" type="button"
        class="flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none">
        <span
            class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor"
                viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
            </svg>
            <span class="hidden">Next</span>
        </span>
    </button>
</div>
<!-- CAROUSEL: fim -->

<!-- SEÇÃO DE FUNÇÃO SOCIAL: inicio -->
<section class="my-10">
    <div class="container flex flex-col items-center mx-auto w-2/5">
        <img class="w-32" src="{% static 'images/lixo-eletronico.png' %}" alt="">
        <h2 class="py-3 text-4xl font-bold text-center">Conectamos você a diversos coletores da sua cidade!</h2>
        <p class="text-xl text-center">Saiba onde fazer o descarte ou doação próximo da sua casa, ou agende uma coleta a
            domicílio.</p>
    </div>
</section>
<!-- SEÇÃO DE FUNÇÃO SOCIAL: fim -->

<!-- SEÇÃO DE SERVIÇOS: inicio -->
<section class="my-10 pb-10">
    <div class="container mx-auto w-10/12">
        <div>
            <h2 class="text-4xl font-bold text-center pb-9 text-primary-color uppercase">Nossos serviços</h2>
        </div>

        <!-- CARTÕES DE SERVIÇO: inicio -->
        <div class="flex justify-evenly">

            <!-- CARD DE DESCARTAR: inicio -->
            <div class="border border-gray-200 rounded-xl drop-shadow-xl hover:drop-shadow-2xl w-1/2">
                <a href="{% url 'paginas:lista_descartar' %}">
                    <img src="{% static 'images/servico-descarte.png' %}" alt="">
                </a>
            </div>
            <!-- CARD DE DESCARTAR: fim -->

            <!-- CARD DE DOAR: inicio -->
            <div class="border border-gray-200 rounded-xl drop-shadow-xl hover:drop-shadow-2xl w-1/2">
                <a href="{% url 'paginas:lista_doar' %}">
                    <img src="{% static 'images/servico-doacao.png' %}" alt="">
                </a>
            </div>
            <!-- CARD DE DOAR: fim -->

        </div>
        <!-- CARTÕES DE SERVIÇO: fim -->

    </div>
</section>
<!-- SEÇÃO DE SERVIÇOS: fim -->

<!-- SEÇÃO DE TESTEMUNHOS: inicio -->
<section class="wy-10">
    <div class="container mx-auto w-1/2 flex flex-col justify-center items-center text-center">

        <div class="mb-8">
            <h2 class="text-4xl font-bold text-center text-primary-color py-3 uppercase">Seja  nosso parceiro</h2>
            <p class="text-xl">Para organizações que reciclam e/ou recebem doações.</p>
        </div>

        <!-- CARD DE PARCEIROS: inicio -->
        <div class="border border-gray-200 rounded-xl drop-shadow-xl hover:drop-shadow-2xl w-5/12 mb-10 maxHeight-5/12 ">
            <a href="{% url 'perfil:coletor_registro' %}">
                <img src="https://conteudo.imguol.com.br/c/noticias/2014/07/10/29mar2011---funcionario-separa-lixo-eletronico-em-fabrica-de-reciclagem-na-provincia-de-hubei-china-1405021145033_615x300.jpg" alt="">
            </a>
        </div>
        <!-- CARD DE PARCEIROS: fim -->

        <div class="mb-3">
            <h2 class="text-4xl font-bold text-center text-primary-color py-3 uppercase">Testemunhos</h2>
            <p class="text-xl">Que nossos clientes falam de nós.</p>
        </div>

        <div class="overflow-hidden rounded-full my-6">
            <img class="w-32" src="{% static 'images/testemunho-joao.png' %}" alt="foto" />
        </div>

        <div>
            <blockquote class="italic px-7">
                Em minhas viagens tive contato com muitos locais poluidos, muitas
                vezes por baterias e eletronicos, o que mexeu comigo. Por isso, <span class="font-bold">estou
                    feliz de ter encontrado a plataforma Recicle! e agora poder descartar
                    esse material perigoso de forma segura para o meio ambiente</span>.
            </blockquote>
        </div>

        <div class="mt-3 self-end text-right text-xs">
            <h4 class="font-bold">João Alexandre S. Meneses</h4>
            <span>Servidor Publico Municipal</span>
        </div>
    </div>
</section>
<!-- SEÇÃO DE TESTEMUNHOS: fim -->

<!-- SEÇÃO DE POSTS: inicio -->
<section class="my-10">

    <div class="container mx-auto w-10/12">

        <div class="w-full text-center mb-3">
            <h2 class="text-4xl py-3 font-bold text-center text-primary-color uppercase">Conteúdos mais recentes</h2>
            <span class="text-xl">Materiais educativos, notícias e curiosidades.</span>
        </div>

        <!-- POSTAGENS: inicio -->
        <div class="w-full my-6 flex justify-between">

            <!-- POST #1: inicio -->
            <div class="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md">
                <a href="{% url 'posts:post-1' %}">
                    <img class="rounded-t-lg w-100" src="{% static 'images/mobile-thumb.jpg' %}" alt="">
                </a>
                <div class="p-5">
                    <a href="{% url 'posts:post-1' %}">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">O que é o lixo eletrônico</h5>
                    </a>
                    <p class="mb-3 font-normal text-gray-700">O Lixo Eletrônico possui muitos nomes, como e-lixo,
                        resíduos de equipamento ...</p>
                    <a href="{% url 'posts:post-1' %}"
                        class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-primary-color rounded-lg hover:bg-secondary-color focus:ring-4 focus:outline-none focus:hover:bg-secondary-color">
                        Continue lendo
                        <svg class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <!-- POST #1: fim -->

            <!-- POST #2: inicio -->
            <div class="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md">
                <a href="{% url 'posts:post-2' %}">
                    <img class="rounded-t-lg w-100" src="{% static 'images/computadores-thumb.jpg' %}" alt="">
                </a>
                <div class="p-5">
                    <a href="{% url 'posts:post-2' %}">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">10 Razões para reciclar o lixo
                            eletrônico</h5>
                    </a>
                    <p class="mb-3 font-normal text-gray-700">Segundo pesquisa da StEP (Solving the E-waste Problem),
                        organização criada pela Universidade das Nações Unidas (UNU) para criar .. ...</p>
                    <a href="{% url 'posts:post-2' %}"
                        class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-primary-color rounded-lg hover:bg-secondary-color focus:ring-4 focus:outline-none focus:hover:bg-secondary-color">
                        Continue lendo
                        <svg class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <!-- POST #2: fim -->

            <!-- POST #3: inicio -->
            <div class="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md">
                <a href="{% url 'posts:post-3' %}">
                    <img class="rounded-t-lg w-100" src="{% static 'images/descartando-televisores.jpg' %}" alt="">
                </a>
                <div class="p-5">
                    <a href="{% url 'posts:post-3' %}">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Como descartar o lixo
                            eletrônico?</h5>
                    </a>
                    <p class="mb-3 font-normal text-gray-700">Ao descartar lixo eletrônico, não desmonte o produto.
                        Coloque-o no coletor, ou entregue ao catador, inteiro. ...</p>
                    <a href="{% url 'posts:post-3' %}"
                        class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-primary-color rounded-lg hover:bg-secondary-color focus:ring-4 focus:outline-none focus:hover:bg-secondary-color">
                        Continue lendo
                        <svg class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </a>
                </div>
            </div>
            <!-- POST #3: fim -->

        </div>
        <!-- POSTAGENS: fim -->

    </div>
</section>
<!-- SEÇÃO DE POSTS: fim -->

<!-- PRINCIPAL: fim -->
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/flowbite.js' %}"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

paginas/templates/paginas/sobre.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sobre - Recicle!{% endblock %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- CONTEUDO PRINCIPAL inicio -->


<section class="mt-6 container mx-auto">
    <div>
        <div class="flex flex-col items-center">
            <img class="w-1/3 mb-9" src="{% static 'images/sobre.png' %}" alt="">
            <h1 class="text-center text-3xl text-primary-color font-bold mb-6 uppercase">Sobre o projeto Recicle</h1>
        </div>
    </div>
    <div class="text-justify mb-16 w-2/3 container mx-auto">
        <p class="">O “Recicle” surgiu em 2020, a partir do desejo de seus idealizadores em contribuir com o meio
            ambiente.</p>
        <p>Possui o objetivo de intermediar o contato entre organizações que fazem reciclagem de lixo
            eletrônico e pessoas que querem contribuir com a natureza através da destinação adequada dos
            resíduos.</p>
    </div>
</section>

<!-- CONTEUDO PRINCIPAL fim  -->
{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

paginas/templates/paginas/termos_de_uso.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sobre - Recicle!{% endblock %}

{% block css %}
{% endblock %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- CONTEUDO PRINCIPAL inicio -->


<section class="mt-6 container mx-auto">
    <div>
        <div class="flex flex-col items-center">
            <img class="w-1/3 mb-9" src="{% static 'images/termos.png' %}" alt="">
            <h1 class="text-center text-3xl text-primary-color font-bold mb-6 uppercase">Termos de Uso</h1>
        </div>
    </div>
    <div class="text-justify mb-16 w-2/3 container mx-auto">

        <h2 class="text-2xl font-bold mb-3">Responsabilidade on-line</h2>

        <p>O Recicle defende a liberdade para troca de ideias, por isso acredita que comentários, opiniões e interações
            entre os usuários tornam o conteúdo do site mais completo e interessante. No entanto, certas conversas podem
            causar mal-entendidos. Para evitar transtornos ao internauta, apresentamos algumas regras para convivência
            on-line no ambiente do site. Seguindo esses passos, será possível estabelecer uma interação produtiva,
            saudável e baseada no respeito mútuo.</p>

        <h2 class="text-2xl font-bold mb-3">Identidade</h2>

        <p>Sempre forneça seus dados exatos e verdadeiros para a sua própria segurança. Essas informações são protegidas
            e
            não estão abertas à consulta, exceção feita às autoridades que obtiverem determinação judicial.
            Moderação</p>

        <p>Nós, do Recicle, oferecemos um espaço de discussão e troca de comentários sobre os conteúdos do site. Porém,
            acreditamos que os usuários devem se manifestar com responsabilidade e respeito às leis brasileiras para que
            ocorram trocas de informação relevantes e baseadas no respeito.</p>

        <p>Deste modo, textos, imagens ou quaisquer materiais em desacordo com tais preceitos poderão ser removidos do
            nosso endereço eletrônico.</p>

        <h2 class="text-2xl font-bold mb-3">Será considerada infração a publicação de conteúdo:</h2>

        <ol class="list-decimal">
            <li>Ilegal;</li>
            <li>Abusivo ou ameaçador;</li>
            <li>Pornográfico, malicioso, obsceno ou profano;</li>
            <li>Difamatório de qualquer natureza;</li>
            <li>Discriminatório de credo, raça, cor, condição física /social ou orientação sexual;</li>
            <li>De incitação à violência e/ou ao crime;</li>
            <li>Capaz de ferir a reputação de pessoas ou organizações;</li>
            <li>Que configure plágio ou produzido por terceiros, sem autorização para publicação;</li>
            <li>De propaganda política, produto ou serviço;</li>
            <li>Mensagens suspeitas de vírus, correntes ou links para sites suspeitos;</li>
            <li>Mensagens de autoria falsa, com conteúdo falso ou fraudulento ou que divulguem informações pessoais, por
                questões de segurança;</li>
            <li>Que viole o direito de propriedade de uma pessoa ou empresa;</li>
            <li>Por poder serem interpretados como agressão, não serão permitidos textos com caixa alta;</li>
            <li>Comentários fora do contexto da matéria publicada.</li>
        </ol>

        <h2 class="text-2xl font-bold mb-3">As consequências por infração a estas regras:</h2>

        <ul class="list-disc">
            <li>Nós, do Recicle, reservamo-nos o direito de eliminar, sem consulta, toda e qualquer mensagem que fira
                diretamente as regras acima estabelecidas;</li>
            <li>Caso haja qualquer dúvida ou sugestão sobre este Código de Conduta, entre em <a class="font-bold"
                    href="#">contato</a>.
            </li>
        </ul>

    </div>
</section>

<!-- CONTEUDO PRINCIPAL fim  -->
{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}