paginas/urls.py
from django.urls import path

from . import views

app_name = "paginas"

urlpatterns = [
    path("", views.index, name="index"),
    path("descartar/", views.descartes, name="lista_descartar"),
    path(
        "coletar/",
        views.coletas,
        name="lista_coletar",
    ),
    path("doar/", views.doacoes, name="lista_doar"),
    path("sobre/", views.sobre, name="sobre"),
    path("termos-de-uso/", views.termos_de_uso, name="termos_de_uso"),
    path(
        "politica-de-privacidade/",
        views.politica_de_privacidade,
        name="politica_de_privacidade",
    ),
    # Simula coletores
    path("coletores/sucata-digital", views.coletor1, name="coletor_1"),
    path("coletores/e-mile", views.coletor2, name="coletor_2"),
    path("coletores/bh-recicla", views.coletor3, name="coletor_3"),
    path("coletores/reciclo-inteligencia-ambiental", views.coletor4, name="coletor_4"),
    path("coletores/mg-recicla", views.coletor5, name="coletor_5"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('o-que-e-o-lixo-eletronico', views.post1, name='post-1'),
    path('10-razoes-para-reciclar-o-lixo-eletronico', views.post2, name='post-2'),
    path('como-descartar-o-lixo-eletronico', views.post3, name='post-3'),
]

recicle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('paginas.urls')),
    path('', include('contatos.urls')),
    path('blog/', include('posts.urls')),
    path('mensagens/', include('mensagens.urls')),
    path('perfil/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

# configura a pagina de erro 404
handler404 = "paginas.views.view_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ADMINISTRAÇÃO DO SISTEMA RECICLE!'
admin.site.site_title = 'RECICLE ADMIN'

contatos/models.py
from django.contrib.auth.models import User
from django.db import models


class ContatoSimples(models.Model):

    nome_remetente = models.CharField(
        verbose_name='Nome', max_length=50
    )

    email = models.EmailField(
        verbose_name='E-mail'
    )

    assunto = models.CharField(
        verbose_name='Assunto',
        max_length=255
    )

    mensagem = models.TextField(
        verbose_name='Mensagem'
    )

    status = models.BooleanField(
        verbose_name='Status (contato aberto/contato não aberto)',
        default=False
    )

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return f'{self.nome_remetente}, {self.assunto}'


class ContatoLGPD(models.Model):

    nome_remetente = models.CharField(
        verbose_name='Nome', max_length=50
    )

    email = models.EmailField(
        verbose_name='E-mail'
    )

    assunto = models.CharField(
        verbose_name='Assunto',
        max_length=255
    )

    mensagem = models.TextField(
        verbose_name='Mensagem'
    )

    status = models.BooleanField(
        verbose_name='Contato aberto',
        default=False
    )

    class Meta:
        verbose_name = 'LPGD'
        verbose_name_plural = 'LGPD'

    def __str__(self):
        return f'{self.nome_remetente}, {self.assunto}'

paginas/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.text import slugify


class Pagina(models.Model):

    STATUS = (
        ('rascunho', 'Rascunho'),
        ('publicado', 'Publicado'),
    )

    titulo = models.CharField(
        verbose_name="Título",
        max_length=255
    )

    slug = models.SlugField(
        max_length=255
    )

    autor = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    conteudo_pagina = models.TextField(
        verbose_name="Conteúdo"
    )
  
    data_criacao = models.DateTimeField(
        auto_now_add=True
    )

    data_modificacao = models.DateTimeField(
        auto_now=True
    )

    publicacao = models.DateTimeField(
        default=timezone.now
    )

    status = models.CharField(max_length=10,
                              choices=STATUS,
                              default='rascunho')

    
    class Meta:
        ordering = ['-publicacao']

    def __str__(self):
        return self.titulo


@receiver(post_save, sender=Pagina)
def insert_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.titulo)
        return instance.save()

paginas/forms.py
from django import forms

# create your form here

paginas/views.py
from django.shortcuts import render

from . import forms


# página inicial
def index(request):
    return render(request, "paginas/index.html")


# página de listagem para descarte
def descartes(request):
    return render(request, "paginas/listagem/descartes.html")


# página de listagem para doações
def doacoes(request):
    return render(request, "paginas/listagem/doacoes.html")


# página de cadastro de coletor
def coletas(request):
    return render(request, "paginas/listagem/coletor_registro.html")


# página sobre
def sobre(request):
    return render(request, "paginas/sobre.html")


# página de termos de uso
def termos_de_uso(request):
    return render(request, "paginas/termos_de_uso.html")


# página de politica de privacidade
def politica_de_privacidade(request):
    return render(request, "paginas/politica_de_privacidade.html")


# página para error 404 (página não encontrada)
def view_404(request, exception):
    return render(request, "not_found.html")


# Simulação de coletores
def coletor1(request):
    return render(request, "paginas/coletores_detalhes/coletor_1.html")


def coletor2(request):
    return render(request, "paginas/coletores_detalhes/coletor_2.html")


def coletor3(request):
    return render(request, "paginas/coletores_detalhes/coletor_3.html")


def coletor4(request):
    return render(request, "paginas/coletores_detalhes/coletor_4.html")


def coletor5(request):
    return render(request, "paginas/coletores_detalhes/coletor_5.html")

paginas/templates/paginas/listagem/coletor_registro.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! - Cadastro de Coletores{% endblock %}


{% comment %} {% block header %}
  {% include "includes/header_simples.html" %}
{% endblock %} {% endcomment %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

<section>
  
  <!-- FORMULÁRIO: inicio -->
  <div class="bg-primary-color" style = "height:25rem; padding-left:3rem;">
    <div class="header-body-2">
      <h2 class="text-left text-3xl mb-3 font-bold text-white font-bold uppercase" style="padding-top:5rem;">Estamos felizes que você deseja ser nosso parceiro</h2>
      <p class="text-white text-2xl font-bold" style="padding-top:2rem;">O primeiro passo será preencher esse formulário de cadastro</p>
    </div>
  </div>

  <div class="container py-3 mx-auto">
    <form class="flex flex-col items-center" style = "background-color: rgba(245, 245, 245);border-radius: 10px;display: flex;width: 45rem;height: 50rem;margin: -150px 0px 100px 400px;border: 3px solid rgba(230, 230, 230);" method="post">
      {% csrf_token %}
      {% if user_form.errors %}
      <div class="bg-red-100 p-3 mb-3">
        <ul>
        {% for label, text in user_form.errors.items %}
          <li>{{ text }}</li>
        {% endfor %}
        </ul>
      </div>
      {% endif %}

      <h1 class="text-3xl mb-3 " style="align-text:left;">Seus Dados</h1>

      <div class="bg-primary-color mb-9" style="width:38rem;height:1px;"></div>

      <div class="mb-3" style="">
        <label class="block font-bold text-xs mb-1" style="width:100%;" for="id_username">Empresa:</label>
        {{ user_form.username }}
      </div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="id_email">CNPJ:</label>
        {{ user_form.email }}
      </div>

      <h1 class="text-3xl mb-3 " style="align-text:left;">Endereço</h1>

      <div class="bg-primary-color mb-9" style="width:38rem;height:1px;"></div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="user_form.email">Rua:</label>
        {{ user_form.email }}
      </div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="user_form.email">Bairro:</label>
        {{ user_form.email }}
      </div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="user_form.email">Complemento:</label>
        {{ user_form.email }}
      </div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="user_form.email">Cidade:</label>
        {{ user_form.email }}
      </div>

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="user_form.email">Itens Trabalhados:</label>
        {{ user_form.email }}
      </div>

      <div class="mt-3 bg-green-100">
        <button class="bg-primary-color px-6 py-2 text-white rounded">Continuar</button>
      </div>

    </form>
        <!-- FORMULÁRIO: fim -->
  </div>
</section>



<!-- PRINCIPAL: fim -->
{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

paginas/templates/paginas/listagem/descartes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! - Descartes{% endblock %}

{% block header %}
    {% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- CONTEUDO PRINCIPAL inicio -->

<div class="py-6 bg-primary-color">
    <div class="container mx-auto text-center flex flex-col items-center">
        <h2 class="pt-3 pb-9 text-6xl text-white font-bold">DESCARTAR</h2>
    </div>
</div>

<div class="my-3 hidden">
    <div class="container mx-auto flex justify-center">
        <form class="mt-9" method="POST">
            <label for="" class="font-bold">Faça a sua pesquisa aqui:</label>
            <input class="p-2" type="text" placeholder="Pesquisar">
            <a class="bg-secondary-color relative rounded p-3 text-white font-bold" type="submit" href="#">Ok</a>
        </form>
    </div>
</div>

<section class="my-9">
    <div class="container mx-auto flex flex-col items-center">

        <a href="{% url 'paginas:coletor_1' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/sucata-digital.jpg' %}" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Sucata Digital
                </h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    Nós realizamos o gerenciamento do lixo eletrônico gerado em empresas e residências, garantindo a destinação final.
                </p>
                
            </div>
        </a>

        <a href="{% url 'paginas:coletor_2' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresa-coleta-lampadas-01.jpg' %}" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    E-MILE Reciclagem de Lixo Eletrônico
                </h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    Te ajudamos a descartar seus resíduos eletroeletrônicos corretamente, evitando ainda mais danos ao meio ambiente.
                </p>
            </div>
        </a>

        <a href="{% url 'paginas:coletor_3' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresa-descarte-pilhas-01.jpg' %}" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    BH Recicla
                </h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    De celulares antigos esquecidos em gavetas a geladeiras paradas. Que tal se livrar desses resíduos?
                </p>
            </div>
        </a>


        <a href="{% url 'paginas:coletor_4' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresa-reciclagem-preco-01.jpg' %}" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Reciclo Inteligência Ambiental 
                </h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    Compramos todo tipo de sucata eletrônica. Entrem em contato conosco, estamos a disposição.
                </p>
            </div>
        </a>

        
        <a href="{% url 'paginas:coletor_5' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresas-reciclagem-impressoras-04.jpg' %}" alt="">
            <div class="flex flex-col justify-between p-4 leading-normal">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    MG Recicla
                </h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    Realizamos a coleta do seu lixo eletrônico de forma simples e gratuita. Estamos aqui para melhor atendê-lo.
                </p>
            </div>
        </a>


    </div>
</section>

<!-- CONTEUDO PRINCIPAL fim  -->
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}

paginas/templates/paginas/listagem/detalhes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contato - Recicle!{% endblock %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}

<section class="my-16">
  <div class="container mx-auto flex items-center justify-center">
    <div>
      <form class="flex flex-col items-center">
        <h1 class="text-center text-3xl text-primary-color font-bold mb-6 uppercase">Detalhes</h1>
        <p class="mb-6">
          <label class="block text-xs font-bold">Usuário</label>
          <input class="rounded-lg" required="required" type="text" />
        </p>

        <p class="mb-6">
          <label class="block text-xs font-bold">E-mail</label>
          <input class="rounded-lg" required="required" type="text" />
        </p>

        <p class="mb-6">
          <label class="block text-xs font-bold">Telefone</label>
          <input class="rounded-lg" required="required" type="text" />
        </p>

        <h2 class="uppercase text-sm text-center font-bold text-primary-color">Conteúdo da mensagem</h2>

        <p class="mb-6">
          <label class="block text-xs font-bold">Assunto</label>
          <input class="rounded-lg" required="required" type="text" />
        </p>

        <p class="mb-6">
          <label class="block text-xs font-bold">Mensagem</label>
          <input class="rounded-lg" required="required" type="text" />
        </p>

        <p class="text-center">
          <button class="bg-primary-color px-6 py-2 font-bold text-white rounded">Enviar Mensagem</button>
        </p>
        <img class="w-2/3" src="{% static 'images/mail.png' %}" alt="">
      </form>
    </div>
  </div>
</section>
{% endblock %}


{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

{% block js %}
<script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

paginas/templates/paginas/listagem/doacoes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! - Doações{% endblock %}

{% block header %}
    {% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- CONTEUDO PRINCIPAL inicio -->

<div class="py-6 bg-primary-color">
  <div class="container mx-auto text-center flex flex-col items-center">
    <h2 class="pt-3 pb-9 text-6xl text-white font-bold">DOAR</h2>
  </div>
</div>

<div class="my-3 hidden">
  <div class="container mx-auto flex justify-center">
    <form class="mt-9" method="POST">
      <label for="" class="font-bold">Faça a sua pesquisa aqui:</label>
      <input class="p-2" type="text" placeholder="Pesquisar">
      <a class="bg-secondary-color relative rounded p-3 text-white font-bold" type="submit" href="#">Ok</a>
    </form>
  </div>
</div>

<section class="mt-9">
  <div class="container mx-auto flex flex-col items-center">

    <a href="{% url 'paginas:coletor_2' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
      <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresa-coleta-lampadas-01.jpg' %}" alt="">
      <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              E-MILE Reciclagem de Lixo Eletrônico
          </h5>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
              Te ajudamos a descartar seus resíduos eletroeletrônicos corretamente, evitando ainda mais danos ao meio ambiente.
          </p>
      </div>
  </a>    

  <a href="{% url 'paginas:coletor_5' %}" class="my-6 flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <img class="object-cover w-full h-96 rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{% static 'images/empresas-reciclagem-impressoras-04.jpg' %}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            MG Recicla
        </h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
            Realizamos a coleta do seu lixo eletrônico de forma simples e gratuita. Estamos aqui para melhor atendê-lo.
        </p>
    </div>
  </a>


  </div>
</section>

<!-- CONTEUDO PRINCIPAL fim  -->
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}