paginas/urls.py
from django.urls import path

from . import views

app_name = "paginas"

urlpatterns = [
    path("", views.index, name="index"),
    path("descartar/", views.descartes, name="lista_descartar"),
    path(
        "coletar/",
        views.coletas,
        name="lista_coletar",
    ),
    path("doar/", views.doacoes, name="lista_doar"),
    path("sobre/", views.sobre, name="sobre"),
    path("termos-de-uso/", views.termos_de_uso, name="termos_de_uso"),
    path(
        "politica-de-privacidade/",
        views.politica_de_privacidade,
        name="politica_de_privacidade",
    ),
    # Simula coletores
    path("coletores/sucata-digital", views.coletor1, name="coletor_1"),
    path("coletores/e-mile", views.coletor2, name="coletor_2"),
    path("coletores/bh-recicla", views.coletor3, name="coletor_3"),
    path("coletores/reciclo-inteligencia-ambiental", views.coletor4, name="coletor_4"),
    path("coletores/mg-recicla", views.coletor5, name="coletor_5"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('o-que-e-o-lixo-eletronico', views.post1, name='post-1'),
    path('10-razoes-para-reciclar-o-lixo-eletronico', views.post2, name='post-2'),
    path('como-descartar-o-lixo-eletronico', views.post3, name='post-3'),
]

recicle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('paginas.urls')),
    path('', include('contatos.urls')),
    path('blog/', include('posts.urls')),
    path('mensagens/', include('mensagens.urls')),
    path('perfil/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

# configura a pagina de erro 404
handler404 = "paginas.views.view_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ADMINISTRAÇÃO DO SISTEMA RECICLE!'
admin.site.site_title = 'RECICLE ADMIN'

usuarios/urls.py
from django.urls import path

from . import views

app_name = "perfil"

urlpatterns = [
    path("coletor/novo", views.RegistroColetor.as_view(), name="coletor_registro"),
    path("coletor/editar", views.EditarColetor.as_view(), name="coletor_edicao"),
    path(
        "consumidor/novo",
        views.RegistroConsumidor.as_view(),
        name="consumidor_registro",
    ),
    path(
        "consumidor/editar", views.EditarConsumidor.as_view(), name="consumidor_edicao"
    ),
]

# views relativas ao processo de autenticação e administração se senhas
urlpatterns += [
    path("entrar/", views.UsuarioLoginView.as_view(), name="login"),
    path("sair/", views.UsuarioLogoutView.as_view(), name="logout"),
    path(
        "alterar-senha/",
        views.UsuarioPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "alterar-senha/sucesso/",
        views.UsuarioPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "resetar-senha/",
        views.UsuarioPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "resetar-senha/<uidb64>/<token>/",
        views.UsuarioPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "resetar-senha/concluido/",
        views.UsuarioPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "resetar-senha/sucesso/",
        views.UsuarioPasswordResetDoneView.as_view(),
        name="password_change_done",
    ),
]

contatos/models.py
from django.contrib.auth.models import User
from django.db import models


class ContatoSimples(models.Model):

    nome_remetente = models.CharField(
        verbose_name='Nome', max_length=50
    )

    email = models.EmailField(
        verbose_name='E-mail'
    )

    assunto = models.CharField(
        verbose_name='Assunto',
        max_length=255
    )

    mensagem = models.TextField(
        verbose_name='Mensagem'
    )

    status = models.BooleanField(
        verbose_name='Status (contato aberto/contato não aberto)',
        default=False
    )

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return f'{self.nome_remetente}, {self.assunto}'


class ContatoLGPD(models.Model):

    nome_remetente = models.CharField(
        verbose_name='Nome', max_length=50
    )

    email = models.EmailField(
        verbose_name='E-mail'
    )

    assunto = models.CharField(
        verbose_name='Assunto',
        max_length=255
    )

    mensagem = models.TextField(
        verbose_name='Mensagem'
    )

    status = models.BooleanField(
        verbose_name='Contato aberto',
        default=False
    )

    class Meta:
        verbose_name = 'LPGD'
        verbose_name_plural = 'LGPD'

    def __str__(self):
        return f'{self.nome_remetente}, {self.assunto}'

usuarios/forms.py
from dataclasses import field

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.models import User

from .models import Consumidor, ColetorModel, EnderecoModel


# formulário de login customizado
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(
        widget=forms.TextInput(attrs={"class": "", "placeholder": ""})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "", "placeholder": ""})
    )


class UsuarioRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Senha", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repita a senha", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Senhas diferentes.")
        return cd["password2"]


class UsuarioEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class ConsumidorEditForm(forms.ModelForm):
    class Meta:
        model = Consumidor
        fields = ["usuario", "tipo"]


class ColetorEditForm(forms.ModelForm):
    class Meta:
        model = ColetorModel
        fields = ["usuario", "tipo"]


class UploadForm(forms.ModelForm):
    empresa = forms.TextInput()
    cnpj = forms.TextInput()
    rua = forms.TextInput()
    bairro = forms.TextInput()
    cidade = forms.TextInput()
    estado = forms.TextInput()
    cep = forms.TextInput
    complemento = forms.TextInput()
    telefone = forms.TextInput()
    itens_trabalhados = forms.TextInput()

    class Meta:
        model = EnderecoModel
        fields = [
            "empresa",
            "cnpj",
            "rua",
            "bairro",
            "cidade",
            "estado",
            "cep",
            "complemento",
            "telefone",
            "itens_trabalhados",
        ]

usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from usuarios.forms import UploadForm
from usuarios.models import EnderecoModel
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, View

from . import forms, models
import psycopg2

# incluir os códigos aqui!


def insere_dados_bd(dados):

    print(dados, "\n\n", dados.get("cidade"))

    empresa = dados.get("empresa")
    cnpj = dados.get("cnpj")
    logradouro = dados.get("rua")
    numero = "7"
    bairro = dados.get("bairro")
    cidade = dados.get("cidade")
    estado = dados.get("estado")
    cep = dados.get("cep")
    complemento = dados.get("complemento")

    SQL = """insert into public.usuarios_enderecomodel values (nextval('public.usuarios_enderecomodel_id_seq'), '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}') """.format(
        logradouro, numero, complemento, bairro, cidade, estado, cep, empresa, cnpj
    )

    conn = psycopg2.connect(
        host="ec2-3-211-221-185.compute-1.amazonaws.com",
        database="d9dsm2atrh8v4q",
        user="thkabhsxdvyvvq",
        password="d717f4a440e9e7ba5a0eeb9bcf9492fb419f97ce07a18e1442cfe30bfcca95ed",
    )
    cursor = conn.cursor()

    resposta = 0

    try:
        cursor.execute(SQL)
        conn.commit()
        cursor.close()
        conn.close()

        resposta = 1

    except Exception as e:
        print("exception obter_id_aluno:", e)
        return -1
    return resposta


class RegistroConsumidor(View):
    def get(self, request):
        user_form = forms.UsuarioRegistrationForm()
        return render(
            request, "usuarios/consumidor_registro.html", {"user_form": user_form}
        )

    def post(self, request):
        user_form = forms.UsuarioRegistrationForm(request.POST)

        if user_form.is_valid():
            # Cria um objeto para o novo usuario, sem salvar o mesmo
            new_user = user_form.save(commit=False)

            # Define a senha escolhida
            new_user.set_password(user_form.cleaned_data["password"])

            # Salva o objeto User
            new_user.save()
            print("new_user:", new_user)

            # Cria o perfil do usuario
            models.Consumidor.objects.create(usuario=new_user)

            return render(
                request, "usuarios/registro_concluido.html", {"new_user": new_user}
            )

        else:
            return render(
                request, "usuarios/consumidor_registro.html", {"user_form": user_form}
            )


class EditarConsumidor(LoginRequiredMixin, View):
    def get(self, request):
        account_form = forms.UsuarioEditForm(instance=request.user)
        consumer_form = forms.ConsumidorEditForm(instance=request.user.profile)

        try:
            profile_picture = True
            print(request.user.profile.profile_picture.url)
        except:
            profile_picture = False

        return render(
            request,
            "usuarios/editar.html",
            {
                "account_form": account_form,
                "consumer_form": consumer_form,
                "profile_picture": profile_picture,
            },
        )

    def post(self, request):
        account_form = forms.UsuarioEditForm(instance=request.user, data=request.POST)
        consumer_form = forms.ConsumidorEditForm(
            instance=request.user.profile, data=request.POST, files=request.FILES
        )

        if account_form.is_valid() and consumer_form.is_valid():
            account_form.save()
            consumer_form.save()

        try:
            profile_picture = True
            print(request.user.profile.profile_picture.url)
        except:
            profile_picture = False

        return render(
            request,
            "usuarios/editar.html",
            {
                "account_form": account_form,
                "consumer_form": collector_form,
                "profile_picture": profile_picture,
            },
        )


class EditarColetor(LoginRequiredMixin, View):
    def get(self, request):
        user_form = forms.UsuarioEditForm(instance=request.user)
        collector_form = forms.ColetorEditForm(instance=request.user)

        try:
            profile_picture = True
            print(request.user.profile.profile_picture.url)
        except:
            profile_picture = False

        return render(
            request,
            "usuarios/editar.html",
            {
                "user_form": user_form,
                "collector_form": collector_form,
                "profile_picture": profile_picture,
            },
        )

    def post(self, request):
        user_form = forms.UsuarioEditForm(instance=request.user, data=request.POST)
        collector_form = forms.ColetorEditForm(
            instance=request.user, data=request.POST, files=request.FILES
        )

        if user_form.is_valid() and collector_form.is_valid():
            user_form.save()
            collector_form.save()

        try:
            profile_picture = True
            print(request.user.profile.profile_picture.url)
        except:
            profile_picture = False

        return render(
            request,
            "usuarios/editar.html",
            {
                "user_form": user_form,
                "collector_form": collector_form,
                "profile_picture": profile_picture,
            },
        )


class UsuarioLoginView(LoginView):
    template_name = "registration/login.html"
    authentication_form = forms.UserLoginForm


class UsuarioLogoutView(LogoutView):
    template_name = "registration/logged_out.html"


class UsuarioPasswordChangeView(PasswordChangeView):
    template_name = "registration/password_change_form.html"


class UsuarioPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = "registration/password_change_done.html"


class UsuarioPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "registration/password_reset_complete.html"


class UsuarioPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"


class UsuarioPasswordResetDoneView(PasswordResetDoneView):
    template_name = "registration/password_reset_done.html"


class UsuarioPasswordResetView(PasswordResetView):
    template_name = "registration/password_reset_form.html"


# class RegistroColetor(View):
#     def get(self, request):
#         user_form = forms.UsuarioRegistrationForm()
#         return render(
#             request, "usuarios/coletor_registro.html", {"user_form": user_form}
#         )

#     def post(self, request):
#         user_form = forms.UsuarioRegistrationForm(request.POST)

#         if user_form.is_valid():
#             # Cria um objeto para o novo usuario, sem salvar o mesmo
#             new_user = user_form.save(commit=False)

#             # Define a senha escolhida
#             new_user.set_password(user_form.cleaned_data["password"])

#             # Salva o objeto User
#             new_user.save()

#             # Cria o perfil do usuario
#             models.Coletor.objects.create(usuario=new_user)

#             return render(
#                 request, "usuarios/registro_concluido.html", {"new_user": new_user}
#             )

#         else:
#             return render(
#                 request, "usuarios/coletor_registro.html", {"user_form": user_form}
#             )


class RegistroColetor(View):
    def get(self, request):
        user_form = forms.UploadForm()
        return render(
            request, "usuarios/coletor_registro.html", {"user_form": user_form}
        )

    def post(self, request):

        insere_dados_bd(request.POST)
        user_form = forms.UploadForm(request.POST)

        if user_form.is_valid():
            # Cria um objeto para o novo usuario, sem salvar o mesmo
            new_user = user_form.save(commit=False)

            # Define a senha escolhida
            # new_user.set_password(user_form.cleaned_data["password"])

            # Salva o objeto User
            # new_user.save()

            # Cria o perfil do usuario
            # models.EnderecoModel.objects.create(usuario=new_user)

            return render(
                request,
                "usuarios/registro_coletor_concluido.html",
                {"new_user": new_user},
            )

        else:
            return render(
                request, "usuarios/coletor_registro.html", {"user_form": user_form}
            )


# def RegistroColetor(request):
#     if request.POST:
#         print("1", request.POST)
#         form = UploadForm(request.POST)

#         return redirect(
#             request, "usuarios/registro_concluido.html", {"user_form": UploadForm}
#         )
#     return render(request, "usuarios/coletor_registro.html", {"user_form": UploadForm})

usuarios/templates/usuarios/coletor_registro.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! - Cadastro de Coletores{% endblock %}


{% block header %}
  {% include "includes/header_simples.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

<section class="my-6">
    <div class="container py-3 mx-auto">
        <!-- FORMULÁRIO: inicio -->
        <form class="flex flex-col items-center" method="post">
          {% csrf_token %}
          <div class="mb-6 text-center">
            <h2 class="text-6xl mb-1 font-bold">Seja nosso Parceiro!</h2>
            <p>Inscreva-se usando o formulário abaixo para e junte-se ao nosso ecossistema.</p>
          </div>

          {% if user_form.errors %}
          <div class="bg-red-100 p-3 mb-3">
            <ul>
            {% for label, text in user_form.errors.items %}
              <li>{{ text }}</li>
            {% endfor %}
            </ul>
          </div>
          {% endif %}

          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_username">Usuário (Obrigatório):</label>
            {{ user_form.username }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_email">Endereço de email (Obrigatório):</label>
            {{ user_form.email }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_password">Senha (Obrigatório):</label>
            {{ user_form.password }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_password2">Repita a senha (Obrigatório):</label>
            {{ user_form.password2 }}
          </div>
          <div class="mt-3 bg-green-100">
            <button class="bg-primary-color px-6 py-2 text-white rounded">Continuar</button>
          </div>

        </form>
        <!-- FORMULÁRIO: fim -->
    </div>
</section>

<!-- PRINCIPAL: fim -->
{% endblock %}

usuarios/templates/usuarios/consumidor_registro.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recicle! - Cadastro de Coletores{% endblock %}


{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

<section>
  <div class="bg-primary-color" style = "height:25rem; padding-left:3rem;">
    <div class="header-body-2">
      <h2 class="text-left text-3xl mb-3 font-bold text-white font-bold uppercase" style="padding-top:5rem; width:43rem;">Estamos felizes que você quer descartar o lixo eletrônico de forma segura</h2>
      <p class="text-white text-2xl font-bold" style="padding-top:2rem;">O primeiro passo será preencher esse formulário de cadastro</p>
    </div>
  </div>

    <div class="container py-3 mx-auto">
        <!-- FORMULÁRIO: inicio -->
        <form class="flex flex-col items-center" style = "background-color: rgba(245, 245, 245);border-radius: 10px;display: flex;width: 45rem;height: 35rem;margin: -150px 0px 100px 400px;border: 3px solid rgba(230, 230, 230);" method="post">
          {% csrf_token %}

          {% if user_form.errors %}
          <div class="bg-red-100 p-3 mb-3">
            <ul>
            {% for label, text in user_form.errors.items %}
              <li>{{ text }}</li>
            {% endfor %}
            </ul>
          </div>
          {% endif %}

          <h1 class="text-3xl mb-3 " style="align-text:left;">Informações para acesso</h1>

          <div class="bg-primary-color mb-3" style="width:38rem;height:1px;"></div>

          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_email">Usuário</label>
            {{ user_form.username }}
          </div>
          
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_email">E-mail</label>
            {{ user_form.email }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_password">Confirmação de e-mail</label>
            {{ user_form.email }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_username">Senha</label>
            {{ user_form.password }}
          </div>
          <div class="mb-3">
            <label class="block font-bold text-xs mb-1" for="id_password2">Confirmação de senha</label>
            {{ user_form.password2 }}
          </div>
          <div class="mt-3 bg-green-100">
            <button class="bg-primary-color px-6 py-2 text-white rounded">Continuar</button>
          </div>

        </form>
        <!-- FORMULÁRIO: fim -->
    </div>
</section>

<!-- PRINCIPAL: fim -->
{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

usuarios/templates/usuarios/editar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Perfil - Recicle!{% endblock %}

{% block css %}
{% endblock %}

{% block header %}
{% include "includes/header.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

<section class="my-6">
  <div class="container py-3 mx-auto">
    <!-- FORMULÁRIO: inicio -->
    <form class="flex flex-col items-center" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-6 text-center">
        <h2 class="text-3xl mb-1 font-bold">Olá <span class="text-primary-color">{{ request.user.username }}</span>,
          edite seus dados</h2>
        <p>Use o formulário abaixo para alterar as suas informações pessoais.</p>
      </div>

      {% if user_form.errors or collector_form.errors %}
      <div class="bg-red-100 p-3 mb-3">
        <ul>
          {% for label, text in user_form.errors.items %}
          <li>{{ text }}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="bg-red-100 p-3 mb-3">
        <ul>
          {% for label, text in collector_form.errors.items %}
          <li>{{ text }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="id_first_name">Primeiro nome:</label>
        {{ user_form.first_name }}
      </div>
      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="id_last_name">Último nome:</label>
        {{ user_form.last_name }}
      </div>
      <div class="mb-3">
        <label class="block font-bold text-xs mb-1" for="id_email">Endereço de email:</label>
        {{ user_form.email }}
      </div>

      {% if photo %}
      <div class="overflow-hidden rounded-2xl my-6 w-48 border shadow-2xl">
        <img src="{{ request.user.profile.photo.url }}" alt="">
      </div>
      {% endif %}

      <div class="mb-3 bg-green-100 p-2">
        <label class="block font-bold text-xs mb-1" for="id_photo">Sua foto de perfil:</label>
        {{ collector_form.profile_picture }}
      </div>
      <div class="mt-3 bg-green-100">
        <button class="bg-primary-color px-6 py-2 text-white rounded">Salvar</button>
      </div>

    </form>
    <!-- FORMULÁRIO: fim -->

    <div class="mt-9">
      <div class="container mx-auto text-center">
        <h3 class="uppercase text-sm"><a href="{% url 'perfil:password_change' %}">Alterar senha</a></h3>
      </div>
    </div>

  </div>
</section>

<!-- PRINCIPAL: fim -->
{% endblock %}

{% block footer %}
{% include "includes/footer.html" %}
{% endblock %}

usuarios/templates/usuarios/registro_coletor_concluido.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}BEM-VINDO! | Recicle!{% endblock %}

{% block css %}{% endblock %}

{% block header %}
{% include "includes/header_simples.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

    <section>
        <div class="my-6 container mx-auto flex flex-col items-center">
            <div class="">
                <img class="w-52" src="{% static 'images/confetti.gif' %}" alt="">
            </div>
            <div class="text-center">
                <h2 class="text-3xl" style="margin-bottom: 20px">Olá, seja bem-vindo(a)!</h2>
                <h3 class="text-4xl" style="margin-bottom: 20px">Em até 7 dias sua empresa estará visível para descartes!</h3>
            </div>
            <div class="text-center text-secondary-color mt-4">
                <a class="font-bold my-3" href="{% url 'perfil:login' %}">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                    <span class="uppercase"> Realizar login</span>
                </a>
            </div>
            <div class="text-center mt-4">
                <a href="{% url 'paginas:index' %}">Voltar para a Homepage</a>
            </div>
        </div>
    </section>

<!-- PRINCIPAL: fim -->
{% endblock %}

usuarios/templates/usuarios/registro_concluido.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}BEM-VINDO! | Recicle!{% endblock %}

{% block css %}{% endblock %}

{% block header %}
{% include "includes/header_simples.html" %}
{% endblock %}

{% block content %}
<!-- PRINCIPAL: inicio -->

    <section>
        <div class="my-6 container mx-auto flex flex-col items-center">
            <div class="">
                <img class="w-52" src="{% static 'images/confetti.gif' %}" alt="">
            </div>
            <div class="text-center">
                <h2 class="text-3xl">Olá, seja bem-vindo(a)!</h2>
                <p>Seu cadastro foi realizado com sucesso.</p>
            </div>
            <div class="text-center text-secondary-color mt-4">
                <a class="font-bold my-3" href="{% url 'perfil:login' %}">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                    <span class="uppercase"> Realizar login</span>
                </a>
            </div>
            <div class="text-center mt-4">
                <a href="{% url 'paginas:index' %}">Voltar para a Homepage</a>
            </div>
        </div>
    </section>

<!-- PRINCIPAL: fim -->
{% endblock %}